### ISSUE TITLE
Error when running with Elastic Search Version 6.x

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-api#159]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior

Should build ES index

## Current Behavior

Receive error when trying to build ES index with newest version of ES
![image](https://user-images.githubusercontent.com/4313463/35303974-dfe74020-0061-11e8-9853-e053ad195020.png)

## Possible Solution

Requires migration to newer version and changing some of the JSON definition files

## Steps to Reproduce (for bugs)

1. install 6.x version of Elastic Search
2. npm run index

## Context

I'm trying to run backend in dev env

## Your Environment

* Version used:
* Browser Name and version: 
* Operating System and version (desktop or mobile): Ubuntu 16.04
* Link to your project:

**Comment by froi** [comment]
This issue is caused by changes in the way Elasticsearch uses types in the index mappings. 

The best solution would be to update the mappings to support Elasticsearch versions 5.6+. Usage of Elasticsearch with versions lower than 5.6 should be discouraged.

As far as I know, the mapping types are similar if not the same between 5.6 and 6.x+.

Another possible solution is to have mappings per supported Elasticsearch version and handle the use of the mappings by checking a config variable that states what version to use.

**Comment by froi** [comment]
More information on Elasticsearch mappings here: https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html

**Comment by froi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Search results don't always match search term #Sprint_35](https://trello.com/c/qMvyTDbr/904-search-results-dont-always-match-search-term-sprint35)
