### ISSUE TITLE
Add Fields to Repos Endpoint

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-api#169]
## Expected Behavior

Would like to be able to get the name of the license and languages from the repos endpoint

## Current Behavior

Get repo field, but is inconsistent and often includes url
There doesn't appear to be a language property

## Context

Need this information to display languages and license on search results page at /search

**Comment by froi** [comment]
There are two ways of doing this. 

1. The basic information for a repo on Github returns the language with the highest percent of code. This could be used but there will be projects, like Django projects, that are more helpful to see the language as Python and not HTML.
2. The second way is to query for the languages themselves and return only the languages that are above a threshold, say 25%.

I'm going to go the threshold route since it will let us show more relevant info.

**Comment by DanielJDufour** [comment]
I was wrong about the license.  That's a part of schema 2.0 and being returned on staging

**Comment by froi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Fields to Repos Endpoint](https://trello.com/c/tEttubAz/587-add-fields-to-repos-endpoint)

**Comment by froi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Integrate API with Search #Sprint_19 #Sprint_22 #Sprint_23 #Sprint_24](https://trello.com/c/Iphow2ev/453-integrate-api-with-search-sprint19-sprint22-sprint23)

**Comment by DanielJDufour** [comment]
This appears to be complete (from our end).  Licenses and Languages are being returned when it has been provided to us.  (Please reopen if I misunderstood)
